### ISSUE TITLE
ImportError: No module named neopixel

### ISSUE THREAD

**Issue by Gadgetoid** [rpi-ws281x/rpi-ws281x-python#10]
```
>>> import neopixel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named neopixel
```

The "neopixel" module was a compatibility shim, with no functionality of its own and has been dropped from this library as of Version 4.0.0. Use `import rpi_ws281x` for exactly the same functionality and API.

**Comment by zc1342303** [comment]
> ```
> >>> import neopixel
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named neopixel
> ```
> 
> 
>      
>   
> 
> The "neopixel" module was a compatibility shim, with no functionality of its own and has been dropped from this library as of Version 4.0.0. Use `import rpi_ws281x` for exactly the same functionality and API.

Thanks a lot, it works for me.
