### ISSUE TITLE
Detected a memory leak of type 'ws2811_t *', no destructor found.

### ISSUE THREAD

**Issue by nicofirst1** [rpi-ws281x/rpi-ws281x-python#48]
As mentioned [here](https://github.com/jgarff/rpi_ws281x/issues/263#issuecomment-652890701) I am trying to to run a custom script where I initiate the class as:

```
from rpi_ws281x import PixelStrip
np= PixelStrip(pixels,PIN) 
np.begin()
```

I am working on Raspberry Pi 4 Model B Rev 1.2 with Python 3.7.3 and running the script with sudo.
The error is the following:
```
Traceback (most recent call last):
  File "src/raspberrypi/main.py", line 23, in <module>
    app = pat(handler=PiHandler, rate=rate, pixels=64, color=color)
  File "/home/pi/Repos/ledypie/src/patterns/chasing.py", line 13, in __init__
    super().__init__(**kwargs)
  File "/home/pi/Repos/ledypie/src/patterns/default.py", line 19, in __init__
    self.handler=handler(rate)
  File "/home/pi/Repos/ledypie/src/raspberrypi/pi_handler.py", line 11, in __init__
    self.np= PixelStrip(pixels,PIN)
  File "/usr/local/lib/python3.7/dist-packages/rpi_ws281x/rpi_ws281x.py", line 95, in __init__
    ws.ws2811_channel_t_count_set(self._channel, num)
TypeError: in method 'ws2811_channel_t_count_set', argument 2 of type 'int'
swig/python detected a memory leak of type 'ws2811_t *', no destructor found.
```
I installed the library with `sudo pip3 install rpi_ws281x` which yielded no errors.

**Comment by nicofirst1** [comment]
I finally fixed the issue.
I was passing the `pixels` value to the `PixelStrip(pixels,PIN)` as a float instead of an int.

**Comment by danpe** [comment]
For me it happens straight from the example  https://github.com/rpi-ws281x/rpi-ws281x-python/blob/3f7f031b8a87f584fcef72225b7cfb1cff682316/examples/lowlevel.py#L65

**Comment by weber-moritz** [comment]
@danpe same here. Do you remember by any chance how you fixed it?

**Comment by infernodemon875** [comment]
@weber-moritz do you by chance remember fixing this? having the same issue just with a test script i wrote myself

**Comment by weber-moritz** [comment]
@infernodemon875 

i have no idea, this is the code i used in the end. cant remember anymore, but this code ran for several months:

```python
from time import sleep
import RPi.GPIO as GPIO
from rpi_ws281x import Adafruit_NeoPixel


# LED strip configuration:
LED_COUNT      = 22       # Number of LED pixels.
LED_PIN        = 18      # GPIO pin connected to the pixels (18 uses PWM!).
#LED_PIN        = 10      # GPIO pin connected to the pixels (10 uses SPI /dev/spidev0.0).
LED_FREQ_HZ    = 800000  # LED signal frequency in hertz (usually 800khz)
LED_DMA        = 10      # DMA channel to use for generating a signal (try 10)
LED_BRIGHTNESS = 65      # Set to 0 for darkest and 255 for brightest
LED_INVERT     = False   # True to invert the signal (when using NPN transistor level shift)
LED_CHANNEL    = 0       # set to '1' for GPIOs 13, 19, 41, 45 or 53

strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
# Intialize the library (must be called once before other functions).
strip.begin()
strip.setBrightness(LED_BRIGHTNESS)


#fill the whole stripe
def led_fill (color):
    for i in range(LED_COUNT):
        strip.setPixelColorRGB(i, color[0], color[1], color[2])
        strip.show()

#breathing animation (fade in and out)
def led_breathe(speed, count, color, brighntess_min, brightness_max, steps):
    
    for j in range(count):
        for i in range(brighntess_min, brightness_max, steps):
            led_fill(tuple(int((i/255)*x) for x in color))
            sleep(speed/1000.0)
            
        for i in range(brightness_max, brighntess_min, -steps):
            led_fill(tuple(int((i/255)*x) for x in color))
            sleep(speed/1000.0)
            
    led_fill((0,0,0))
    strip.show()


#to handle overflow of led_count for circle
def int_to_index(i):
    if i < 0:
        #print("smaller", LED_COUNT+i)
        return LED_COUNT+i
    elif i > LED_COUNT-1:
        #print("bigger", i - LED_COUNT)
        return i - LED_COUNT
    else:
        #print("nothing", i)
        return i


#circle animation (led turning in circles)
def led_circle(speed, count, color, brightness):
    for j in range(count):
        for i in range(0, LED_COUNT + 1):
            #led_fill((0,0,0))
            brightness_scaler = (brightness/255)
            strip.setPixelColorRGB(i, int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            brightness_scaler = (brightness/400)
            strip.setPixelColorRGB(int_to_index(i+1), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            strip.setPixelColorRGB(int_to_index(i-1), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            brightness_scaler = (brightness/1000)
            strip.setPixelColorRGB(int_to_index(i+2), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            strip.setPixelColorRGB(int_to_index(i-2), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            brightness_scaler = (brightness/1500)
            strip.setPixelColorRGB(int_to_index(i+2), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            strip.setPixelColorRGB(int_to_index(i-2), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            strip.setPixelColorRGB(int_to_index(i+3), 0,0,0)
            strip.setPixelColorRGB(int_to_index(i-3), 0,0,0)
            
            strip.show()
            sleep(speed/1000.0)
        
    #led_fill((0,0,0))
    #strip.show()

#led flashes with fade out
def led_flash(speed, count, color, brightness):
    for i in range(count+1):
        for j in range(10,0, -1):
            led_fill(tuple(int(((brightness/10)*j/255)*x) for x in color))
            strip.show()
            sleep(speed/1000.0)
    
    led_fill((0,0,0))
    strip.show()

#led blinks on and off
def led_blink(speed, count, color, brightness):
    for i in range(count+1):
        for j in range(0,2):
            led_fill(tuple(j*int((brightness/255)*x) for x in color))
            strip.show()
            sleep(speed/1000.0)
            
    led_fill((0,0,0))
    strip.show()
    

#fills up the circle with  a color
def led_fill_circle(speed, count, direction, color, brightness):
    new_range = range(0, int(LED_COUNT))
    
    if direction == -1:
        new_range = range(int(LED_COUNT +1 ), -1, -1)
    
    for j in range(0, count):
        for i in new_range: #range(0, int(LED_COUNT/2)+1):
            
            brightness_scaler = (brightness/255)
            strip.setPixelColorRGB(i, int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            brightness_scaler = (brightness/800)
            strip.setPixelColorRGB(max(0, min(i-1*direction, LED_COUNT)), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            brightness_scaler = (brightness/2000)
            strip.setPixelColorRGB(max(0, min(i-2*direction, LED_COUNT)), int(brightness_scaler*color[0]), int(brightness_scaler*color[1]), int(brightness_scaler*color[2]))
            
            strip.show()
            sleep(speed/1000.0)

def select_animation(animation_type, repetition):
    base_color = (255, 50, 255)
    try:
        if animation_type == 0:
            #print("breathe")
            led_breathe(0.0, int(repetition), base_color, 5, 40, 2)
        elif animation_type == 1:
            #print("circle")
            led_circle(20, repetition, base_color, 80)
        elif animation_type == 2:
            #print("welcome")
            #led_flash(7, 3, (100, 255, 50), 150)
            led_fill_circle(15, 3, -1, (100, 255, 50), 200)
        elif animation_type == 3:
            #print("goodbye")
            #led_flash(15, 2, (100, 0, 255), 200)
            led_fill_circle(30, 2, -1, (100, 0, 255), 200)
        elif animation_type == 4:
            #print("not available. Loading")
            led_fill((100, 32, 0))
        elif animation_type == -1:
            #print("error")
            led_blink(75, 3, (255, 0, 0), 200)
        elif animation_type == -2:
            #print("error")
            led_blink(125, repetition, (255, 0, 0), 200)
    except:
        print("-led-\t", "Error")
```

**Comment by infernodemon875** [comment]
Ok thanks anyways @weber-moritz, also thank you for posting your code, as I'm not very familiar with this stuff it was very helpful to see examples of the types of things you can do with it.
